### ISSUE TITLE
 Magento 2 on FrankenPHP

### ISSUE THREAD

**Issue by jonatanaxe** [faradey/madock#20]
Hi @faradey Do you believe it is possible to run Magento 2 with "FrankenPHP https://frankenphp.dev/ The Modern PHP App Server, written in Go "? Have you studied or heard of any practical cases where this was done? What would be the potential challenges and benefits of this approach?

**Comment by faradey** [comment]
Hi @jonatanaxe,
Currently, the assembly uses nginx as an HTTP(s) server.
And not only PHP but also NodeJS works on its basis. Perhaps several more platforms and programming languages ​​will be added in the future.

FrankenPHP cannot become a standard for all platforms and programming languages since it is tightly connected with PHP.
I would also like to know what advantages FrankenPHP gives for local development, in addition to the similarity of the local environment with the remote server.

You can also try to make a new branch and rewrite the configuration files so that they include FrankenPHP support. To do this, you will need to remove Nginx support and add FrankenPHP support.

**Comment by jonatanaxe** [comment]
@faradey Cool and interesting. Thanks for your insight, Madock.
